/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProduccionRouteImport } from './routes/produccion'
import { Route as PozosYCohortesRouteImport } from './routes/pozos-y-cohortes'
import { Route as MetodologiaRouteImport } from './routes/metodologia'
import { Route as MapaRouteImport } from './routes/mapa'
import { Route as FracturasRouteImport } from './routes/fracturas'
import { Route as DescargasRouteImport } from './routes/descargas'
import { Route as CalidadRouteImport } from './routes/calidad'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OperadoresIndexRouteImport } from './routes/operadores/index'
import { Route as PeriodosReleaseIdRouteImport } from './routes/periodos/$releaseId'
import { Route as OperadoresSlugRouteImport } from './routes/operadores/$slug'

const ProduccionRoute = ProduccionRouteImport.update({
  id: '/produccion',
  path: '/produccion',
  getParentRoute: () => rootRouteImport,
} as any)
const PozosYCohortesRoute = PozosYCohortesRouteImport.update({
  id: '/pozos-y-cohortes',
  path: '/pozos-y-cohortes',
  getParentRoute: () => rootRouteImport,
} as any)
const MetodologiaRoute = MetodologiaRouteImport.update({
  id: '/metodologia',
  path: '/metodologia',
  getParentRoute: () => rootRouteImport,
} as any)
const MapaRoute = MapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => rootRouteImport,
} as any)
const FracturasRoute = FracturasRouteImport.update({
  id: '/fracturas',
  path: '/fracturas',
  getParentRoute: () => rootRouteImport,
} as any)
const DescargasRoute = DescargasRouteImport.update({
  id: '/descargas',
  path: '/descargas',
  getParentRoute: () => rootRouteImport,
} as any)
const CalidadRoute = CalidadRouteImport.update({
  id: '/calidad',
  path: '/calidad',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OperadoresIndexRoute = OperadoresIndexRouteImport.update({
  id: '/operadores/',
  path: '/operadores/',
  getParentRoute: () => rootRouteImport,
} as any)
const PeriodosReleaseIdRoute = PeriodosReleaseIdRouteImport.update({
  id: '/periodos/$releaseId',
  path: '/periodos/$releaseId',
  getParentRoute: () => rootRouteImport,
} as any)
const OperadoresSlugRoute = OperadoresSlugRouteImport.update({
  id: '/operadores/$slug',
  path: '/operadores/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calidad': typeof CalidadRoute
  '/descargas': typeof DescargasRoute
  '/fracturas': typeof FracturasRoute
  '/mapa': typeof MapaRoute
  '/metodologia': typeof MetodologiaRoute
  '/pozos-y-cohortes': typeof PozosYCohortesRoute
  '/produccion': typeof ProduccionRoute
  '/operadores/$slug': typeof OperadoresSlugRoute
  '/periodos/$releaseId': typeof PeriodosReleaseIdRoute
  '/operadores/': typeof OperadoresIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calidad': typeof CalidadRoute
  '/descargas': typeof DescargasRoute
  '/fracturas': typeof FracturasRoute
  '/mapa': typeof MapaRoute
  '/metodologia': typeof MetodologiaRoute
  '/pozos-y-cohortes': typeof PozosYCohortesRoute
  '/produccion': typeof ProduccionRoute
  '/operadores/$slug': typeof OperadoresSlugRoute
  '/periodos/$releaseId': typeof PeriodosReleaseIdRoute
  '/operadores': typeof OperadoresIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calidad': typeof CalidadRoute
  '/descargas': typeof DescargasRoute
  '/fracturas': typeof FracturasRoute
  '/mapa': typeof MapaRoute
  '/metodologia': typeof MetodologiaRoute
  '/pozos-y-cohortes': typeof PozosYCohortesRoute
  '/produccion': typeof ProduccionRoute
  '/operadores/$slug': typeof OperadoresSlugRoute
  '/periodos/$releaseId': typeof PeriodosReleaseIdRoute
  '/operadores/': typeof OperadoresIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calidad'
    | '/descargas'
    | '/fracturas'
    | '/mapa'
    | '/metodologia'
    | '/pozos-y-cohortes'
    | '/produccion'
    | '/operadores/$slug'
    | '/periodos/$releaseId'
    | '/operadores/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calidad'
    | '/descargas'
    | '/fracturas'
    | '/mapa'
    | '/metodologia'
    | '/pozos-y-cohortes'
    | '/produccion'
    | '/operadores/$slug'
    | '/periodos/$releaseId'
    | '/operadores'
  id:
    | '__root__'
    | '/'
    | '/calidad'
    | '/descargas'
    | '/fracturas'
    | '/mapa'
    | '/metodologia'
    | '/pozos-y-cohortes'
    | '/produccion'
    | '/operadores/$slug'
    | '/periodos/$releaseId'
    | '/operadores/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalidadRoute: typeof CalidadRoute
  DescargasRoute: typeof DescargasRoute
  FracturasRoute: typeof FracturasRoute
  MapaRoute: typeof MapaRoute
  MetodologiaRoute: typeof MetodologiaRoute
  PozosYCohortesRoute: typeof PozosYCohortesRoute
  ProduccionRoute: typeof ProduccionRoute
  OperadoresSlugRoute: typeof OperadoresSlugRoute
  PeriodosReleaseIdRoute: typeof PeriodosReleaseIdRoute
  OperadoresIndexRoute: typeof OperadoresIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/produccion': {
      id: '/produccion'
      path: '/produccion'
      fullPath: '/produccion'
      preLoaderRoute: typeof ProduccionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pozos-y-cohortes': {
      id: '/pozos-y-cohortes'
      path: '/pozos-y-cohortes'
      fullPath: '/pozos-y-cohortes'
      preLoaderRoute: typeof PozosYCohortesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metodologia': {
      id: '/metodologia'
      path: '/metodologia'
      fullPath: '/metodologia'
      preLoaderRoute: typeof MetodologiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapa': {
      id: '/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof MapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fracturas': {
      id: '/fracturas'
      path: '/fracturas'
      fullPath: '/fracturas'
      preLoaderRoute: typeof FracturasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/descargas': {
      id: '/descargas'
      path: '/descargas'
      fullPath: '/descargas'
      preLoaderRoute: typeof DescargasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calidad': {
      id: '/calidad'
      path: '/calidad'
      fullPath: '/calidad'
      preLoaderRoute: typeof CalidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operadores/': {
      id: '/operadores/'
      path: '/operadores'
      fullPath: '/operadores/'
      preLoaderRoute: typeof OperadoresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/periodos/$releaseId': {
      id: '/periodos/$releaseId'
      path: '/periodos/$releaseId'
      fullPath: '/periodos/$releaseId'
      preLoaderRoute: typeof PeriodosReleaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operadores/$slug': {
      id: '/operadores/$slug'
      path: '/operadores/$slug'
      fullPath: '/operadores/$slug'
      preLoaderRoute: typeof OperadoresSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalidadRoute: CalidadRoute,
  DescargasRoute: DescargasRoute,
  FracturasRoute: FracturasRoute,
  MapaRoute: MapaRoute,
  MetodologiaRoute: MetodologiaRoute,
  PozosYCohortesRoute: PozosYCohortesRoute,
  ProduccionRoute: ProduccionRoute,
  OperadoresSlugRoute: OperadoresSlugRoute,
  PeriodosReleaseIdRoute: PeriodosReleaseIdRoute,
  OperadoresIndexRoute: OperadoresIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
